"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from decouple import Config
from decouple import Config, Csv, AutoConfig
import logging
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
SITE_ID = 1


CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://mouseforce.onrender.com']
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'mouseforce.onrender.com']

  # Permite accesul de oriunde; în producție setează domeniul corect.
SOCIAL_AUTH_GOOGLE_CLIENT_ID = config('SOCIAL_AUTH_GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_SECRET = config('SOCIAL_AUTH_GOOGLE_SECRET')

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = 'allauth.socialaccount.adapter.DefaultSocialAccountAdapter'
ACCOUNT_ADAPTER = 'mouse_force_first_step.accounts.adapters.MyAccountAdapter'
SOCIALACCOUNT_LOGIN_ON_GET = True

LOGIN_REDIRECT_URL = '/accounts/post-login/'


# Application definition

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'mouse_force_first_step' / 'templates',
            BASE_DIR / 'mouse_force_first_step' / 'accounts' / 'templates',
        ],
        'APP_DIRS': True,  # Permite căutarea template-urilor în directoarele aplicațiilor
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
config = AutoConfig()

logging.basicConfig(level=logging.DEBUG)
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'accounts.CustomUser'

# Combine both static folders (frontend and mycookiesprivacy)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mouse_force_first_step', 'homepage', 'static'),
    os.path.join(BASE_DIR, 'mouse_force_first_step', 'mycookieprivacy', 'static'),
]


AUTHENTICATION_BACKENDS = [
    'mouse_force_first_step.accounts.auth_backends.EmailOrUsernameBackend',  # custom login email/username
    'django.contrib.auth.backends.ModelBackend',  # clasic Django
    'allauth.account.auth_backends.AuthenticationBackend',  # pentru Google login
]


BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR:", BASE_DIR) 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'project_name.urls'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # aplicațiile tale
    'mouse_force_first_step.accounts',
    'mouse_force_first_step.customerpanel',
    'mouse_force_first_step.homepage',
    'mouse_force_first_step.myapp',
    'mouse_force_first_step.mycookieprivacy',

    # pentru login cu Google
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # alte third-party apps
    'corsheaders',
]

WSGI_APPLICATION = 'project_name.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "https://mouseforce.onrender.com",  # Your deployed frontend
    "http://localhost:3000",  # Local frontend (if needed)
    "http://127.0.0.1:8080",
]

CORS_ALLOW_ALL_ORIGINS = True  # Enable temporarily for debugging (remove later)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mouseforce_db_camping',
        'USER': 'mouseforce_db_camping_user',
        'PASSWORD': '8GQ04AA7sxdk1Xb6ZwJ3zewVWnULpdsW',
        'HOST': 'dpg-cv1mmm3tq21c73d85ha0-a.oregon-postgres.render.com',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'mouseforce_db_camping',
#         'USER': 'postgres',
#         'PASSWORD': 'unreal89a',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""