"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from decouple import Config
from decouple import Config, Csv, AutoConfig
import logging
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'mouseforce.onrender.com']

  # Permite accesul de oriunde; în producție setează domeniul corect.


# Application definition

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Asigură-te că acest director este corect
        'APP_DIRS': True,  # Permite căutarea template-urilor în directoarele aplicațiilor
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
config = AutoConfig()

logging.basicConfig(level=logging.DEBUG)
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Combine both static folders (frontend and mycookiesprivacy)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'mouse_force_first_step', 'homepage', 'static'),
    os.path.join(BASE_DIR, 'mouse_force_first_step', 'mycookieprivacy', 'static'),
]


BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR:", BASE_DIR) 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'project_name.urls'

INSTALLED_APPS = [
    'django.contrib.admin',  # Admin panel
    'django.contrib.auth',  # Autentificare utilizatori
    'django.contrib.contenttypes',  # Tipuri de conținut
    'django.contrib.sessions',  # Gestionarea sesiunilor
    'django.contrib.messages',  # Mesaje flash
    'django.contrib.staticfiles',  # Fișiere statice (CSS, JS)
    'mouse_force_first_step.accounts',
    'mouse_force_first_step.homepage',
    'mouse_force_first_step.myapp',
    'mouse_force_first_step.mycookieprivacy',
    'corsheaders',
    # Adaugă și aplicațiile tale aici
]

WSGI_APPLICATION = 'project_name.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "https://mouseforce.onrender.com",  # Your deployed frontend
    "http://localhost:3000",  # Local frontend (if needed)
    "http://127.0.0.1:8080",
]

CORS_ALLOW_ALL_ORIGINS = True  # Enable temporarily for debugging (remove later)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'mouseforce_db_camping',
#         'USER': 'mouseforce_db_camping_user',
#         'PASSWORD': '8GQ04AA7sxdk1Xb6ZwJ3zewVWnULpdsW',
#         'HOST': 'dpg-cv1mmm3tq21c73d85ha0-a',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mouseforce_db_camping',
        'USER': 'postgres',
        'PASSWORD': 'unreal89a',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Django settings for project_name project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""